done with 6th module assignment
Deepak1124/disprz-python-project pull request #5
Opened 2023-05-30 11:46 UTC by Deepak1124

2023-05-30 17:36 UTC, tanmaythole requested changes

2023-05-30 17:36 UTC, tanmaythole commented on module-6/filterDigitsAndAlphabets.py
> +for ele in data:
You need to use of inbuilt functions like map, filter, or reduce to implement this question

2023-05-30 17:36 UTC, tanmaythole commented on module-6/getUniqueNos.py
> +
Try alternative solution for this, using set

2023-05-30 17:36 UTC, tanmaythole commented on module-6/replaceDigitsfromListOfStrings.py
> +
You can use regex here

2023-05-31 07:35 UTC, Deepak1124 commented on module-6/getUniqueNos.py
> +
done

2023-05-31 07:36 UTC, Deepak1124 commented on module-6/filterDigitsAndAlphabets.py
> +for ele in data:
done

2023-05-31 07:40 UTC, Deepak1124 commented on module-6/replaceDigitsfromListOfStrings.py
> +
done

2023-05-31 09:14 UTC, tanmaythole approved these changes

2023-06-02 07:36 UTC, merged